'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { getResource, openWhatsApp, postAction } from '@/lib/client';
import { money, shortDate } from '@/lib/format';
import { PageHeader } from '@/components/ui/PageHeader';
import { Loading } from '@/components/ui/Loading';
import { Icon } from '@/components/ui/Icon';
import { Modal } from '@/components/ui/Modal';
import { Toast } from '@/components/ui/Toast';
import { Select } from '@/components/ui/Select';
import { DatePicker } from '@/components/ui/DatePicker';
import { TimePicker } from '@/components/ui/TimePicker';

const eventTypes=['Wedding','Walima','Mehndi','Engagement','Corporate','Other'].map(v=>({value:v,label:v}));
const shifts=['Morning','Evening','Night'].map(v=>({value:v,label:v}));
const bookingStatuses=[{value:'confirmed',label:'Confirm Booking'},{value:'hold',label:'Temporary Hold'}];
const paymentMethods=['Cash','Bank Transfer','JazzCash','Easypaisa','Card'].map(v=>({value:v,label:v}));
const filterStatuses=[{value:'all',label:'All statuses'},{value:'confirmed',label:'Confirmed'},{value:'hold',label:'On hold'},{value:'completed',label:'Completed'},{value:'cancelled',label:'Cancelled'}];

const blank = { customerName:'',phone:'',eventDate:'',shift:'Evening',hallId:'',eventType:'Wedding',guests:300,status:'confirmed',baseRate:3000,stageName:'',stageCost:0,otherCharges:0,discount:0,advance:0,paymentMethod:'Cash',menuItemIds:[] as string[],notes:'',specialInstructions:'',arrivalTime:'18:30',dinnerTime:'21:00' };

export default function BookingsPage(){
  const params=useSearchParams(); const [data,setData]=useState<any>(null); const [form,setForm]=useState({...blank}); const [open,setOpen]=useState(params.get('new')==='1'); const [edit,setEdit]=useState<any>(null); const [saving,setSaving]=useState(false); const [toast,setToast]=useState<{m:string;t:'success'|'error'}|null>(null); const [search,setSearch]=useState(params.get('q')||''); const [status,setStatus]=useState('all');
  async function load(){try{const d=await getResource('bookings');setData(d);setForm(f=>({...f,baseRate:d.settings.defaultBaseRate,hallId:f.hallId||d.halls.find((h:any)=>h.active)?.id||''}))}catch(e){setToast({m:e instanceof Error?e.message:'Load failed',t:'error'})}}
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(params.get('new')==='1')setOpen(true)},[params]);
  const hall=useMemo(()=>data?.halls.find((h:any)=>h.id===form.hallId),[data,form.hallId]);
  const selectedItems=useMemo(()=>data?.menuItems.filter((m:any)=>form.menuItemIds.includes(m.id))||[],[data,form.menuItemIds]);
  const perHead=Number(form.baseRate||0)+selectedItems.reduce((s:number,m:any)=>s+Number(m.priceDelta||0),0);
  const total=Math.max(0,Number(form.guests||0)*perHead+Number(form.stageCost||0)+Number(form.otherCharges||0)-Number(form.discount||0));
  const filtered=(data?.bookings||[]).filter((b:any)=>{const q=search.toLowerCase();const match=!q||[b.code,b.customerName,b.phone,b.eventDate,b.hallName].join(' ').toLowerCase().includes(q);return match&&(status==='all'||b.status===status)});
  function update(name:string,value:any){setForm(f=>({...f,[name]:value}))}
  function toggleMenu(id:string){setForm(f=>({...f,menuItemIds:f.menuItemIds.includes(id)?f.menuItemIds.filter(x=>x!==id):[...f.menuItemIds,id]}))}
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);try{const r:any=await postAction('createBooking',{...form});if(r.whatsapp?.link)openWhatsApp(r.whatsapp.link);setToast({m:`${r.booking.code} ${form.status==='hold'?'held':'confirmed'} successfully.`,t:'success'});setOpen(false);setForm({...blank,baseRate:data.settings.defaultBaseRate,hallId:data.halls.find((h:any)=>h.active)?.id||''});await load()}catch(err){setToast({m:err instanceof Error?err.message:'Could not create booking',t:'error'})}finally{setSaving(false)}}
  async function saveEdit(e:FormEvent){e.preventDefault();if(!edit)return;setSaving(true);try{await postAction('updateBooking',{id:edit.id,guests:Number(edit.guests),stageName:edit.stageName,stageCost:Number(edit.stageCost),specialInstructions:edit.specialInstructions,arrivalTime:edit.arrivalTime,dinnerTime:edit.dinnerTime,menuItemIds:edit.menuItemIds});setEdit(null);setToast({m:'Booking changes saved with audit history.',t:'success'});await load()}catch(err){setToast({m:err instanceof Error?err.message:'Could not update booking',t:'error'})}finally{setSaving(false)}}
  async function changeStatus(id:string,next:string){try{const r:any=await postAction('setBookingStatus',{id,status:next});if(r.whatsapp?.link)openWhatsApp(r.whatsapp.link);setToast({m:`Booking marked ${next}.`,t:'success'});await load()}catch(e){setToast({m:e instanceof Error?e.message:'Update failed',t:'error'})}}
  async function toggleFinalize(id:string){try{await postAction('toggleFinalize',{id});setToast({m:'Booking lock updated.',t:'success'});await load()}catch(e){setToast({m:e instanceof Error?e.message:'Update failed',t:'error'})}}
  if(!data)return <Loading/>;
  return <>
    <PageHeader title="Bookings" description="Create, hold, confirm and control every event booking from one register-free workspace." actions={<button className="btn btn-primary" onClick={()=>setOpen(true)}><Icon name="plus-lg"/>New Booking</button>}/>
    <div className="filterbar"><label className="table-search"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search booking, client, phone or date..."/></label><div style={{width:160}}><Select value={status} options={filterStatuses} onChange={setStatus}/></div><button className="btn" onClick={load}><Icon name="arrow-clockwise"/>Refresh</button></div>
    <section className="panel"><div className="table-scroll"><table className="data-table"><thead><tr><th>Booking</th><th>Customer</th><th>Date / Shift</th><th>Hall</th><th>Guests</th><th>Total</th><th>Balance</th><th>Ready</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((b:any)=><tr key={b.id}><td><strong className="code-text">{b.code}</strong>{b.finalized?<span className="cell-sub"><Icon name="lock-fill" size={11}/> Finalized</span>:null}</td><td><strong>{b.customerName}</strong><span className="cell-sub">{b.phone}</span></td><td>{shortDate(b.eventDate)}<span className="cell-sub">{b.shift}</span></td><td>{b.hallName}</td><td>{b.guests.toLocaleString()}</td><td>{money(b.totalAmount,data.settings.currencySymbol)}<span className="cell-sub">{money(b.perHeadRate,data.settings.currencySymbol)}/head</span></td><td className={b.balance>0?'text-orange':'text-green'}>{money(b.balance,data.settings.currencySymbol)}</td><td><span className={`ready-badge ${b.readiness===100?'complete':''}`}>{b.readiness}%</span></td><td><span className={`status-pill status-${b.status}`}>{b.status}</span></td><td><div className="row-actions"><button title="Edit booking" onClick={()=>setEdit({...b,menuItemIds:b.menuSelections.map((m:any)=>m.itemId)})}><Icon name="pencil"/></button><button title={b.finalized?'Unlock':'Finalize'} onClick={()=>toggleFinalize(b.id)}><Icon name={b.finalized?'unlock':'lock'}/></button>{b.status==='hold'?<button title="Confirm" onClick={()=>changeStatus(b.id,'confirmed')}><Icon name="check2"/></button>:null}{b.status==='confirmed'?<button title="Complete" onClick={()=>changeStatus(b.id,'completed')}><Icon name="check2-circle"/></button>:null}{!['cancelled','completed'].includes(b.status)?<button className="danger" title="Cancel" onClick={()=>changeStatus(b.id,'cancelled')}><Icon name="x-circle"/></button>:null}</div></td></tr>)}{!filtered.length?<tr><td colSpan={10}><div className="empty-row">No bookings match this view.</div></td></tr>:null}</tbody></table></div></section>

    <Modal open={open} title="Create Booking" subtitle="Availability, capacity, menu price and total are validated before the slot is saved." onClose={()=>setOpen(false)} width="980px">
      <form onSubmit={submit}>
        <div className="form-section"><h3>Customer & event</h3><div className="form-grid form-grid-4"><label className="field"><span>Customer Name *</span><input required value={form.customerName} onChange={e=>update('customerName',e.target.value)}/></label><label className="field"><span>Phone *</span><input required value={form.phone} onChange={e=>update('phone',e.target.value)} placeholder="+92 3xx xxxxxxx"/></label><label className="field"><span>Event Type</span><Select value={form.eventType} options={eventTypes} onChange={v=>update('eventType',v)}/></label><label className="field"><span>Guests *</span><input required min="1" type="number" value={form.guests} onChange={e=>update('guests',Number(e.target.value))}/></label></div></div>
        <div className="form-section"><h3>Slot & hall</h3><div className="form-grid form-grid-4"><label className="field"><span>Event Date *</span><DatePicker required value={form.eventDate} onChange={v=>update('eventDate',v)}/></label><label className="field"><span>Shift *</span><Select value={form.shift} options={shifts} onChange={v=>update('shift',v)}/></label><label className="field"><span>Hall *</span><Select value={form.hallId} options={data.halls.filter((h:any)=>h.active).map((h:any)=>({value:h.id,label:`${h.name} (${h.minCapacity}-${h.maxCapacity})`}))} onChange={v=>update('hallId',v)}/></label><label className="field"><span>Booking Status</span><Select value={form.status} options={bookingStatuses} onChange={v=>update('status',v)}/></label></div>{hall?<div className={`capacity-note ${form.guests<hall.minCapacity||form.guests>hall.maxCapacity?'bad':'good'}`}><Icon name={form.guests<hall.minCapacity||form.guests>hall.maxCapacity?'exclamation-triangle':'check-circle'}/>{hall.name} supports {hall.minCapacity}-{hall.maxCapacity} guests. Current guest count: {Number(form.guests||0).toLocaleString()}.</div>:null}</div>
        <div className="form-section"><div className="section-title-row"><h3>Menu & pricing</h3><span className="price-preview">{money(perHead,data.settings.currencySymbol)} / head</span></div><div className="menu-picker">{data.menuItems.map((m:any)=><label key={m.id} className={`menu-option ${form.menuItemIds.includes(m.id)?'selected':''}`}><input type="checkbox" checked={form.menuItemIds.includes(m.id)} onChange={()=>toggleMenu(m.id)}/><span><strong>{m.name}</strong><small>{m.category} · {m.priceDelta?`+${money(m.priceDelta,data.settings.currencySymbol)}/head`:'Included'}</small></span><Icon name="check2"/></label>)}</div><div className="form-grid form-grid-4" style={{marginTop:12}}><label className="field"><span>Base Rate / Head</span><input type="number" min="0" value={form.baseRate} onChange={e=>update('baseRate',Number(e.target.value))}/></label><label className="field"><span>Stage Name</span><input value={form.stageName} onChange={e=>update('stageName',e.target.value)} placeholder="Classic Ivory"/></label><label className="field"><span>Stage Cost</span><input type="number" min="0" value={form.stageCost} onChange={e=>update('stageCost',Number(e.target.value))}/></label><label className="field"><span>Other Charges</span><input type="number" min="0" value={form.otherCharges} onChange={e=>update('otherCharges',Number(e.target.value))}/></label></div></div>
        <div className="form-section"><h3>Payment & event notes</h3><div className="form-grid form-grid-4"><label className="field"><span>Advance Received</span><input type="number" min="0" value={form.advance} onChange={e=>update('advance',Number(e.target.value))}/></label><label className="field"><span>Payment Method</span><Select value={form.paymentMethod} options={paymentMethods} onChange={v=>update('paymentMethod',v)}/></label><label className="field"><span>Arrival Time</span><TimePicker value={form.arrivalTime} onChange={v=>update('arrivalTime',v)}/></label><label className="field"><span>Dinner Time</span><TimePicker value={form.dinnerTime} onChange={v=>update('dinnerTime',v)}/></label></div><label className="field"><span>Special Instructions</span><textarea rows={2} value={form.specialInstructions} onChange={e=>update('specialInstructions',e.target.value)} placeholder="VIP tables, stage notes, special timing, family instructions..."/></label></div>
        <div className="booking-total"><div><span>Per head</span><strong>{money(perHead,data.settings.currencySymbol)}</strong></div><div><span>Guests</span><strong>{Number(form.guests||0).toLocaleString()}</strong></div><div><span>Advance</span><strong>{money(Number(form.advance||0),data.settings.currencySymbol)}</strong></div><div className="grand"><span>Grand Total</span><strong>{money(total,data.settings.currencySymbol)}</strong></div></div>
        <div className="modal-actions"><button type="button" className="btn" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={saving||!form.customerName||!form.eventDate}>{saving?'Saving…':form.status==='hold'?'Hold Slot':'Confirm Booking'}</button></div>
      </form>
    </Modal>

    <Modal open={!!edit} title={edit?`Edit ${edit.code}`:'Edit Booking'} subtitle="Customer changes are saved to the audit trail. Finalized events must be unlocked first." onClose={()=>setEdit(null)} width="820px">
      {edit?<form onSubmit={saveEdit}><div className="form-grid form-grid-4"><label className="field"><span>Guests</span><input type="number" min="1" value={edit.guests} onChange={e=>setEdit({...edit,guests:Number(e.target.value)})}/></label><label className="field"><span>Stage Name</span><input value={edit.stageName||''} onChange={e=>setEdit({...edit,stageName:e.target.value})}/></label><label className="field"><span>Stage Cost</span><input type="number" min="0" value={edit.stageCost||0} onChange={e=>setEdit({...edit,stageCost:Number(e.target.value)})}/></label><label className="field"><span>Arrival Time</span><TimePicker value={edit.arrivalTime||''} onChange={v=>setEdit({...edit,arrivalTime:v})}/></label><label className="field"><span>Dinner Time</span><TimePicker value={edit.dinnerTime||''} onChange={v=>setEdit({...edit,dinnerTime:v})}/></label></div><div className="form-section"><h3>Menu</h3><div className="menu-picker">{data.menuItems.map((m:any)=><label key={m.id} className={`menu-option ${edit.menuItemIds.includes(m.id)?'selected':''}`}><input type="checkbox" checked={edit.menuItemIds.includes(m.id)} onChange={()=>setEdit({...edit,menuItemIds:edit.menuItemIds.includes(m.id)?edit.menuItemIds.filter((x:string)=>x!==m.id):[...edit.menuItemIds,m.id]})}/><span><strong>{m.name}</strong><small>{m.category} · {m.priceDelta?`+${money(m.priceDelta,data.settings.currencySymbol)}/head`:'Included'}</small></span><Icon name="check2"/></label>)}</div></div><label className="field"><span>Special Instructions</span><textarea rows={3} value={edit.specialInstructions||''} onChange={e=>setEdit({...edit,specialInstructions:e.target.value})}/></label><div className="modal-actions"><button type="button" className="btn" onClick={()=>setEdit(null)}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?'Saving…':'Save Changes'}</button></div></form>:null}
    </Modal>
    {toast?<Toast message={toast.m} type={toast.t} onClose={()=>setToast(null)}/>:null}
  </>;
}
