'use client';
import { useEffect, useState } from 'react';
import { getResource, openWhatsApp, postAction } from '@/lib/client';
import { money, dateTime, shortDate } from '@/lib/format';
import { PageHeader } from '@/components/ui/PageHeader';
import { Loading } from '@/components/ui/Loading';
import { Icon } from '@/components/ui/Icon';
import { Toast } from '@/components/ui/Toast';
import { Select } from '@/components/ui/Select';

const modes=[{value:'link',label:'WhatsApp Link (no API required)'},{value:'cloud_api',label:'Meta WhatsApp Cloud API'}];
export default function AutomationsPage(){
 const[data,setData]=useState<any>(null);const[form,setForm]=useState<any>(null);const[toast,setToast]=useState<{m:string;t:'success'|'error'}|null>(null);
 async function load(){const d=await getResource('automations');setData(d);setForm(d.settings)} useEffect(()=>{load()},[]);
 async function save(){try{await postAction('saveAutomations',{automations:form});setToast({m:'Automation settings saved.',t:'success'});await load()}catch(e){setToast({m:e instanceof Error?e.message:'Save failed',t:'error'})}}
 async function remind(id:string){try{const r:any=await postAction('sendPaymentReminder',{bookingId:id});openWhatsApp(r.whatsapp?.link);setToast({m:r.whatsapp?.status==='sent'?'Reminder sent through Cloud API.':'WhatsApp reminder prepared.',t:'success'});await load()}catch(e){setToast({m:e instanceof Error?e.message:'Reminder failed',t:'error'})}}
 if(!data||!form)return <Loading/>;const locked=!!data.readOnlyConfig;
 return <><PageHeader title="WhatsApp Automation" description="Trigger-based communication for booking confirmations, payment reminders, vendor tasks and owner reports." actions={!locked?<button className="btn btn-primary" onClick={save}><Icon name="floppy"/>Save Settings</button>:undefined}/>
 {locked?<div className="alert alert-info" style={{marginBottom:12}}><Icon name="shield-lock"/><span>Automation configuration is locked for demo access. Operational reminder actions remain available to test.</span></div>:null}
 <div className="automation-grid"><section className="panel"><div className="panel-head"><div><h2>Workflow Switches</h2><p>Choose which operational triggers are active.</p></div><button className={`toggle ${form.enabled?'on':''}`} disabled={locked} onClick={()=>setForm({...form,enabled:!form.enabled})}><i/></button></div><div className="settings-list"><Switch label="Booking confirmation receipt" desc="Runs when a booking changes to Confirmed." value={form.bookingReceipt} disabled={locked} on={()=>setForm({...form,bookingReceipt:!form.bookingReceipt})}/><Switch label="Payment reminder" desc="Used for outstanding balances and scheduled reminders." value={form.paymentReminder} disabled={locked} on={()=>setForm({...form,paymentReminder:!form.paymentReminder})}/><Switch label="Vendor task alert" desc="Runs as soon as a vendor task is assigned." value={form.vendorAlert} disabled={locked} on={()=>setForm({...form,vendorAlert:!form.vendorAlert})}/><Switch label="Nightly owner report" desc="Runs at the configured owner report time on a hosted instance." value={form.nightlyOwnerReport} disabled={locked} on={()=>setForm({...form,nightlyOwnerReport:!form.nightlyOwnerReport})}/></div></section>
 <section className="panel"><div className="panel-head"><div><h2>Delivery Mode</h2><p>Use one-click WhatsApp links or connect an approved Meta Cloud API account.</p></div></div><div className="panel-body compact"><label className="field"><span>Mode</span><Select value={form.whatsappMode} options={modes} disabled={locked} onChange={v=>setForm({...form,whatsappMode:v})}/></label><label className="field"><span>Owner WhatsApp</span><input disabled={locked} value={form.ownerPhone} onChange={e=>setForm({...form,ownerPhone:e.target.value})}/></label>{form.whatsappMode==='cloud_api'?<><label className="field"><span>Phone Number ID</span><input disabled={locked} value={form.cloudApiPhoneNumberId} onChange={e=>setForm({...form,cloudApiPhoneNumberId:e.target.value})}/></label><label className="field"><span>Access Token</span><input disabled={locked} type="password" value={form.cloudApiToken} onFocus={()=>form.cloudApiToken==='••••••••'&&setForm({...form,cloudApiToken:''})} onChange={e=>setForm({...form,cloudApiToken:e.target.value})}/></label><div className="alert alert-info"><Icon name="info-circle"/><span>Production outbound reminders may require approved WhatsApp message templates. API credentials remain server-side.</span></div></>:<div className="alert alert-info"><Icon name="whatsapp"/><span>Link mode opens WhatsApp with the complete message already filled in. It works well for demos and venues not yet connected to the Business API.</span></div>}</div></section></div>
 <section className="panel" style={{marginTop:12}}><div className="panel-head"><div><h2>Outstanding Payment Reminders</h2><p>Only confirmed bookings with a remaining balance are shown.</p></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Booking</th><th>Customer</th><th>Event</th><th>Balance</th><th>Action</th></tr></thead><tbody>{data.bookings.filter((b:any)=>b.balance>0).map((b:any)=><tr key={b.id}><td className="code-text">{b.code}</td><td>{b.customerName}<span className="cell-sub">{b.phone}</span></td><td>{shortDate(b.eventDate)} · {b.shift}</td><td className="text-orange">{money(b.balance)}</td><td><button className="btn btn-small" onClick={()=>remind(b.id)}><Icon name="whatsapp"/>Prepare Reminder</button></td></tr>)}{!data.bookings.some((b:any)=>b.balance>0)?<tr><td colSpan={5}><div className="empty-row">No outstanding balances.</div></td></tr>:null}</tbody></table></div></section>
 <section className="panel" style={{marginTop:12}}><div className="panel-head"><div><h2>Automation Log</h2><p>Every prepared, sent or failed message remains auditable.</p></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Time</th><th>Type</th><th>Recipient</th><th>Status</th><th>Message</th></tr></thead><tbody>{data.logs.map((l:any)=><tr key={l.id}><td>{dateTime(l.createdAt)}</td><td>{l.type.replaceAll('_',' ')}</td><td>{l.recipient}</td><td><span className={`status-pill ${l.status==='sent'?'status-confirmed':l.status==='failed'?'status-cancelled':'status-hold'}`}>{l.status}</span></td><td className="log-message">{l.message}</td></tr>)}{!data.logs.length?<tr><td colSpan={5}><div className="empty-row">No automation messages have run yet.</div></td></tr>:null}</tbody></table></div></section>{toast?<Toast message={toast.m} type={toast.t} onClose={()=>setToast(null)}/>:null}</>;
}
function Switch({label,desc,value,on,disabled=false}:{label:string;desc:string;value:boolean;on:()=>void;disabled?:boolean}){return <div className="settings-row"><div><strong>{label}</strong><span>{desc}</span></div><button className={`toggle ${value?'on':''}`} disabled={disabled} onClick={on}><i/></button></div>}
