'use client';
import { FormEvent, useEffect, useState } from 'react';
import { getResource, postAction } from '@/lib/client';
import { money, shortDate } from '@/lib/format';
import { PageHeader } from '@/components/ui/PageHeader';
import { Loading } from '@/components/ui/Loading';
import { Icon } from '@/components/ui/Icon';
import { Modal } from '@/components/ui/Modal';
import { Toast } from '@/components/ui/Toast';
import { Select } from '@/components/ui/Select';
import { DatePicker } from '@/components/ui/DatePicker';

const paymentMethods=['Cash','Bank Transfer','JazzCash','Easypaisa','Card'].map(v=>({value:v,label:v}));
const paymentStatuses=[{value:'verified',label:'Verified'},{value:'pending',label:'Pending Verification'}];
export default function PaymentsPage(){
 const[data,setData]=useState<any>(null);const[open,setOpen]=useState(false);const[form,setForm]=useState({bookingId:'',amount:0,method:'Cash',reference:'',status:'verified',paidAt:new Date().toISOString().slice(0,10),notes:''});const[toast,setToast]=useState<{m:string;t:'success'|'error'}|null>(null);
 async function load(){const d=await getResource('payments');setData(d);setForm(f=>({...f,bookingId:f.bookingId||d.bookings[0]?.id||''}))} useEffect(()=>{load()},[]);
 async function submit(e:FormEvent){e.preventDefault();try{await postAction('recordPayment',form);setOpen(false);setForm({...form,amount:0,reference:'',notes:''});setToast({m:'Payment recorded and balance updated.',t:'success'});await load()}catch(e){setToast({m:e instanceof Error?e.message:'Payment failed',t:'error'})}}
 if(!data)return <Loading/>;
 const collected=data.payments.filter((p:any)=>p.status==='verified').reduce((s:number,p:any)=>s+p.amount,0);const pending=data.bookings.reduce((s:number,b:any)=>s+b.balance,0);
 return <><PageHeader title="Payments" description="Track every advance and installment against the exact booking balance." actions={<button className="btn btn-primary" onClick={()=>setOpen(true)} disabled={!data.bookings.length}><Icon name="plus-lg"/>Record Payment</button>}/>
 <section className="metric-grid metric-grid-3"><div className="metric-card"><span className="metric-icon green"><Icon name="cash-coin"/></span><div><span>Verified Collection</span><strong>{money(collected,data.settings.currencySymbol)}</strong></div></div><div className="metric-card"><span className="metric-icon orange"><Icon name="hourglass-split"/></span><div><span>Outstanding Balance</span><strong>{money(pending,data.settings.currencySymbol)}</strong></div></div><div className="metric-card"><span className="metric-icon blue"><Icon name="receipt"/></span><div><span>Payment Entries</span><strong>{data.payments.length}</strong></div></div></section>
 <section className="panel"><div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Booking</th><th>Customer</th><th>Method</th><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>{data.payments.map((p:any)=><tr key={p.id}><td>{shortDate(p.paidAt)}</td><td className="code-text">{p.booking?.code||'—'}</td><td>{p.booking?.customerName||'—'}</td><td>{p.method}</td><td>{p.reference||'—'}</td><td className="text-green">{money(p.amount,data.settings.currencySymbol)}</td><td><span className={`status-pill ${p.status==='verified'?'status-confirmed':'status-hold'}`}>{p.status}</span></td></tr>)}{!data.payments.length?<tr><td colSpan={7}><div className="empty-row">No payments recorded yet.</div></td></tr>:null}</tbody></table></div></section>
 <Modal open={open} title="Record Payment" subtitle="The booking balance updates immediately and the action is added to the audit history." onClose={()=>setOpen(false)}><form onSubmit={submit}><label className="field"><span>Booking *</span><Select value={form.bookingId} options={data.bookings.map((b:any)=>({value:b.id,label:`${b.code} — ${b.customerName} — Balance ${money(b.balance,data.settings.currencySymbol)}`}))} onChange={v=>setForm({...form,bookingId:v})}/></label><div className="form-grid form-grid-2"><label className="field"><span>Amount *</span><input required min="1" type="number" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></label><label className="field"><span>Method</span><Select value={form.method} options={paymentMethods} onChange={v=>setForm({...form,method:v})}/></label><label className="field"><span>Reference / Receipt No.</span><input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label className="field"><span>Payment Date</span><DatePicker value={form.paidAt} onChange={v=>setForm({...form,paidAt:v})}/></label><label className="field"><span>Status</span><Select value={form.status} options={paymentStatuses} onChange={v=>setForm({...form,status:v})}/></label></div><label className="field"><span>Notes</span><textarea rows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="modal-actions"><button type="button" className="btn" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary">Record Payment</button></div></form></Modal>{toast?<Toast message={toast.m} type={toast.t} onClose={()=>setToast(null)}/>:null}</>;
}
