'use client';
import { useEffect, useMemo, useState } from 'react';
import { getResource } from '@/lib/client';
import { money } from '@/lib/format';
import { PageHeader } from '@/components/ui/PageHeader';
import { Loading } from '@/components/ui/Loading';
import { Icon } from '@/components/ui/Icon';

export default function ReportsPage(){
 const[data,setData]=useState<any>(null);useEffect(()=>{getResource('reports').then(setData)},[]);
 const stats=useMemo(()=>{if(!data)return null;const confirmed=data.bookings.filter((b:any)=>['confirmed','completed'].includes(b.status));const completed=data.bookings.filter((b:any)=>b.status==='completed');const avg=confirmed.length?confirmed.reduce((s:number,b:any)=>s+b.totalAmount,0)/confirmed.length:0;const lost=data.inquiries.filter((i:any)=>i.status==='lost').length;const converted=data.inquiries.filter((i:any)=>i.status==='confirmed').length;const funnelTotal=data.inquiries.length;const conversion=funnelTotal?Math.round(converted/funnelTotal*100):0;const months:Array<{key:string;label:string;amount:number;bookings:number}>=[];for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;months.push({key,label:d.toLocaleString('en',{month:'short'}),amount:0,bookings:0})}for(const p of data.payments){const m=months.find(x=>p.paidAt?.startsWith(x.key));if(m&&p.status==='verified')m.amount+=p.amount}for(const b of confirmed){const m=months.find(x=>b.eventDate?.startsWith(x.key));if(m)m.bookings++}return{confirmed:confirmed.length,completed:completed.length,avg,lost,conversion,months,max:Math.max(1,...months.map(m=>m.amount))}},[data]);
 if(!data||!stats)return <Loading/>;const d=data.dashboard.stats;
 return <><PageHeader title="Reports" description="Simple owner-level numbers: bookings, collections, balances and sales movement without accounting clutter."/>
 <section className="metric-grid"><Metric label="Confirmed Events" value={stats.confirmed} icon="calendar-check"/><Metric label="Total Collected" value={money(d.collected,data.settings.currencySymbol)} icon="cash-stack" tone="green"/><Metric label="Outstanding" value={money(d.pendingBalance,data.settings.currencySymbol)} icon="hourglass-split" tone="orange"/><Metric label="Average Booking" value={money(stats.avg,data.settings.currencySymbol)} icon="calculator" tone="blue"/><Metric label="Inquiry Conversion" value={`${stats.conversion}%`} icon="funnel" tone="purple"/></section>
 <div className="report-grid"><section className="panel"><div className="panel-head"><div><h2>Collection — Last 6 Months</h2><p>Verified payment entries grouped by month.</p></div></div><div className="bar-chart">{stats.months.map(m=><div className="bar-col" key={m.key}><div className="bar-value">{m.amount?money(m.amount,data.settings.currencySymbol).replace(data.settings.currencySymbol,'').trim():'0'}</div><div className="bar-track"><i style={{height:`${Math.max(3,m.amount/stats.max*100)}%`}}/></div><span>{m.label}</span></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Owner Snapshot</h2><p>Operational numbers worth checking every day.</p></div></div><div className="report-list"><div><span>Active follow-ups</span><strong>{d.followUps}</strong></div><div><span>Events in next 7 days</span><strong>{d.upcoming7}</strong></div><div><span>Completed events</span><strong>{stats.completed}</strong></div><div><span>Lost inquiries</span><strong>{stats.lost}</strong></div><div><span>Confirmed bookings total</span><strong>{stats.confirmed}</strong></div></div></section></div>
 <section className="panel" style={{marginTop:12}}><div className="panel-head"><div><h2>Booking Volume</h2><p>Confirmed/completed events by event month.</p></div></div><div className="volume-row">{stats.months.map(m=><div key={m.key}><span>{m.label}</span><strong>{m.bookings}</strong><small>events</small></div>)}</div></section>
 </>;
}
function Metric({label,value,icon,tone=''}:{label:string;value:string|number;icon:string;tone?:string}){return <div className="metric-card"><span className={`metric-icon ${tone}`}><Icon name={icon}/></span><div><span>{label}</span><strong>{value}</strong></div></div>}
