'use client';
import { FormEvent, useEffect, useState } from 'react';
import { getResource, postAction } from '@/lib/client';
import { PageHeader } from '@/components/ui/PageHeader';
import { Loading } from '@/components/ui/Loading';
import { Icon } from '@/components/ui/Icon';
import { Modal } from '@/components/ui/Modal';
import { Toast } from '@/components/ui/Toast';
import { Select } from '@/components/ui/Select';
import { TimePicker } from '@/components/ui/TimePicker';
import { ColorPicker } from '@/components/ui/ColorPicker';

const currencyOptions=['PKR','SAR','AED','USD','GBP'].map(v=>({value:v,label:v}));
const durationOptions=[{value:'24',label:'24 hours'},{value:'72',label:'3 days'},{value:'168',label:'7 days'},{value:'336',label:'14 days'}];

export default function SettingsPage(){
 const[data,setData]=useState<any>(null);const[settings,setSettings]=useState<any>(null);const[hallOpen,setHallOpen]=useState(false);const[hall,setHall]=useState({name:'',minCapacity:100,maxCapacity:400});const[pw,setPw]=useState({currentPassword:'',newPassword:'',confirm:''});const[toast,setToast]=useState<{m:string;t:'success'|'error'}|null>(null);const[access,setAccess]=useState({accessLabel:'',durationHours:'72'});const[credentials,setCredentials]=useState<any>(null);const[confirmAction,setConfirmAction]=useState<{type:'clear'|'revoke';id?:string}|null>(null);
 async function load(){const d=await getResource('settings');setData(d);setSettings(d.settings)}useEffect(()=>{load()},[]);
 async function save(){try{await postAction('saveSettings',{settings});setToast({m:'Venue settings saved. Branding is updating…',t:'success'});setTimeout(()=>window.location.reload(),650)}catch(e){setToast({m:e instanceof Error?e.message:'Save failed',t:'error'})}}
 async function addHall(e:FormEvent){e.preventDefault();try{await postAction('addHall',hall);setHallOpen(false);setHall({name:'',minCapacity:100,maxCapacity:400});await load();setToast({m:'Hall added.',t:'success'})}catch(e){setToast({m:e instanceof Error?e.message:'Could not add hall',t:'error'})}}
 async function toggleHall(id:string){try{await postAction('toggleHall',{id});await load()}catch(e){setToast({m:e instanceof Error?e.message:'Update failed',t:'error'})}}
 async function changePassword(e:FormEvent){e.preventDefault();if(pw.newPassword!==pw.confirm){setToast({m:'New passwords do not match.',t:'error'});return}try{await postAction('changePassword',{currentPassword:pw.currentPassword,newPassword:pw.newPassword});setPw({currentPassword:'',newPassword:'',confirm:''});setToast({m:'Password changed successfully.',t:'success'})}catch(e){setToast({m:e instanceof Error?e.message:'Password change failed',t:'error'})}}
 async function clear(){try{await postAction('clearOperationalData');setConfirmAction(null);setToast({m:'Operational data cleared.',t:'success'})}catch(e){setToast({m:e instanceof Error?e.message:'Could not clear data',t:'error'})}}
 async function createAccess(e:FormEvent){e.preventDefault();try{const r:any=await postAction('createDemoAccess',{accessLabel:access.accessLabel,durationHours:Number(access.durationHours)});setCredentials(r.credentials);setAccess({...access,accessLabel:''});await load();setToast({m:'Temporary demo access created.',t:'success'})}catch(e){setToast({m:e instanceof Error?e.message:'Could not create demo access',t:'error'})}}
 async function revoke(id:string){try{await postAction('revokeDemoAccess',{id});setConfirmAction(null);await load();setToast({m:'Demo access disabled.',t:'success'})}catch(e){setToast({m:e instanceof Error?e.message:'Could not revoke access',t:'error'})}}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setToast({m:'Copied to clipboard.',t:'success'})}catch{setToast({m:'Copy failed. Please select the text manually.',t:'error'})}}
 async function copyAccess(){if(!credentials)return;const text=`Demo Access\nURL: ${window.location.origin}\nUsername: ${credentials.username}\nPassword: ${credentials.password}\nExpires: ${new Date(credentials.expiresAt).toLocaleString()}`;await copy(text)}
 if(!data||!settings)return <Loading/>;
 const isOwner=data.user?.role==='owner';
 return <><PageHeader title="Settings" description="Configure venue identity, booking rules and secure access without changing code." actions={<button className="btn btn-primary" onClick={save}><Icon name="floppy"/>Save Changes</button>}/>
 <div className="settings-grid"><section className="panel"><div className="panel-head"><div><h2>Venue Identity</h2><p>The display name is shown in the workspace header; the legal name is used on documents.</p></div></div><div className="panel-body compact"><div className="form-grid form-grid-2"><label className="field"><span>Marquee Display Name</span><input value={settings.displayName||''} onChange={e=>setSettings({...settings,displayName:e.target.value})} placeholder="Royal Marquee"/></label><label className="field"><span>Legal / Invoice Name</span><input value={settings.legalName} onChange={e=>setSettings({...settings,legalName:e.target.value})}/></label><label className="field"><span>Short Initials</span><input maxLength={3} value={settings.initials} onChange={e=>setSettings({...settings,initials:e.target.value.toUpperCase()})}/></label><label className="field"><span>Accent Color</span><ColorPicker value={settings.accent} onChange={v=>setSettings({...settings,accent:v})}/></label><label className="field"><span>Phone</span><input value={settings.phone} onChange={e=>setSettings({...settings,phone:e.target.value})}/></label><label className="field"><span>Email</span><input value={settings.email} onChange={e=>setSettings({...settings,email:e.target.value})}/></label><label className="field"><span>Address</span><input value={settings.address} onChange={e=>setSettings({...settings,address:e.target.value})}/></label><label className="field"><span>City</span><input value={settings.city} onChange={e=>setSettings({...settings,city:e.target.value})}/></label></div></div></section>
 <section className="panel"><div className="panel-head"><div><h2>Business Rules</h2><p>Configure pricing, advances, slot holds and reporting behavior.</p></div></div><div className="panel-body compact"><div className="form-grid form-grid-2"><label className="field"><span>Currency</span><Select value={settings.currency} options={currencyOptions} onChange={v=>setSettings({...settings,currency:v,currencySymbol:v})}/></label><label className="field"><span>Default Per-Head Rate</span><input type="number" min="0" value={settings.defaultBaseRate} onChange={e=>setSettings({...settings,defaultBaseRate:Number(e.target.value)})}/></label><label className="field"><span>Suggested Advance %</span><input type="number" min="0" max="100" value={settings.advancePercent} onChange={e=>setSettings({...settings,advancePercent:Number(e.target.value)})}/></label><label className="field"><span>Temporary Hold Minutes</span><input type="number" min="5" value={settings.holdMinutes} onChange={e=>setSettings({...settings,holdMinutes:Number(e.target.value)})}/></label><label className="field"><span>Timezone</span><input value={settings.timezone} onChange={e=>setSettings({...settings,timezone:e.target.value})}/></label><label className="field"><span>Owner Report Time</span><TimePicker value={settings.ownerReportTime} onChange={v=>setSettings({...settings,ownerReportTime:v})}/></label></div></div></section></div>
 <section className="panel" style={{marginTop:12}}><div className="panel-head"><div><h2>Hall Sections</h2><p>Capacity matching and double-booking checks use these hall rules.</p></div><button className="btn" onClick={()=>setHallOpen(true)}><Icon name="plus-lg"/>Add Hall</button></div><div className="settings-list">{data.halls.map((h:any)=><div className="settings-row" key={h.id}><div><strong>{h.name}</strong><span>{h.minCapacity.toLocaleString()}–{h.maxCapacity.toLocaleString()} guests</span></div><button className={`toggle ${h.active?'on':''}`} onClick={()=>toggleHall(h.id)} aria-label={`${h.active?'Disable':'Enable'} ${h.name}`}><i/></button></div>)}</div></section>
 {isOwner?<section className="panel" style={{marginTop:12}}><div className="panel-head"><div><h2>Temporary Demo Access</h2><p>Create time-limited credentials for a prospective client. Use this on a dedicated demo workspace; demo users can see that workspace's operational records. Passwords are shown only once.</p></div></div><div className="panel-body"><div className="demo-access-grid"><div><form onSubmit={createAccess}><div className="form-grid form-grid-2"><label className="field"><span>Client / Marquee Label *</span><input required value={access.accessLabel} onChange={e=>setAccess({...access,accessLabel:e.target.value})} placeholder="Royal Marquee Demo"/></label><label className="field"><span>Access Duration</span><Select value={access.durationHours} options={durationOptions} onChange={v=>setAccess({...access,durationHours:v})}/></label></div><button className="btn btn-primary"><Icon name="key"/>Create Temporary Access</button></form>{credentials?<div className="demo-credentials" style={{marginTop:12}}><h3>Share these credentials with the client</h3><div className="credential-row"><span>Username</span><code>{credentials.username}</code><button className="copy-icon-btn" onClick={()=>copy(credentials.username)}><Icon name="copy"/></button></div><div className="credential-row"><span>Password</span><code>{credentials.password}</code><button className="copy-icon-btn" onClick={()=>copy(credentials.password)}><Icon name="copy"/></button></div><div className="credential-row"><span>Expires</span><code>{new Date(credentials.expiresAt).toLocaleString()}</code><button className="copy-icon-btn" onClick={()=>copy(new Date(credentials.expiresAt).toLocaleString())}><Icon name="copy"/></button></div><p className="demo-note">The demo account can test operational workflows, but venue settings and security controls stay locked.</p><button type="button" className="btn btn-small" style={{marginTop:9}} onClick={copyAccess}><Icon name="copy"/>Copy Full Access Message</button></div>:null}</div><div><div className="access-list">{data.demoAccess?.map((a:any)=><div className="access-row" key={a.id}><div><strong>{a.accessLabel}</strong><small>{a.username} · expires {a.expiresAt?new Date(a.expiresAt).toLocaleString():'—'}</small></div><span className={`access-state ${a.expired?'expired':!a.active?'revoked':''}`}>{a.expired?'Expired':a.active?'Active':'Revoked'}</span>{a.active&&!a.expired?<button className="btn btn-small btn-danger" onClick={()=>setConfirmAction({type:'revoke',id:a.id})}>Revoke</button>:<span/>}</div>)}{!data.demoAccess?.length?<div className="empty-mini"><Icon name="key" size={22}/><span>No temporary access created yet.</span></div>:null}</div></div></div></div></section>:null}
 <div className="settings-grid" style={{marginTop:12}}><section className="panel"><div className="panel-head"><div><h2>Account Security</h2><p>Use a strong password before storing real financial data.</p></div></div><div className="panel-body"><form onSubmit={changePassword}><label className="field"><span>Current Password</span><input required type="password" value={pw.currentPassword} onChange={e=>setPw({...pw,currentPassword:e.target.value})}/></label><div className="form-grid form-grid-2"><label className="field"><span>New Password</span><input required minLength={8} type="password" value={pw.newPassword} onChange={e=>setPw({...pw,newPassword:e.target.value})}/></label><label className="field"><span>Confirm New Password</span><input required minLength={8} type="password" value={pw.confirm} onChange={e=>setPw({...pw,confirm:e.target.value})}/></label></div><button className="btn"><Icon name="shield-lock"/>Change Password</button></form></div></section><section className="panel danger-panel"><div className="panel-head"><div><h2>Workspace Data</h2><p>Reset operational demo records while keeping venue configuration.</p></div></div><div className="panel-body"><div className="alert alert-danger"><Icon name="exclamation-triangle"/><span>Clearing removes inquiries, bookings, payments, readiness and tasks. Venue settings, halls, menu and vendors stay.</span></div>{isOwner?<button className="btn btn-danger" onClick={()=>setConfirmAction({type:'clear'})}><Icon name="trash3"/>Clear Operational Data</button>:<p className="demo-note">Only the owner account can clear operational records.</p>}</div></section></div>
 <Modal open={!!confirmAction} title={confirmAction?.type==='clear'?'Clear Operational Data':'Revoke Demo Access'} subtitle={confirmAction?.type==='clear'?'This removes operational demo records but keeps venue configuration.':'The client will be signed out and the credentials will stop working immediately.'} onClose={()=>setConfirmAction(null)}><div className="alert alert-danger"><Icon name="exclamation-triangle"/><span>{confirmAction?.type==='clear'?'Inquiries, bookings, payments, readiness and vendor tasks will be removed.':'This temporary demo access will be disabled.'}</span></div><div className="modal-actions"><button type="button" className="btn" onClick={()=>setConfirmAction(null)}>Cancel</button><button type="button" className="btn btn-danger" onClick={()=>confirmAction?.type==='clear'?clear():confirmAction?.id&&revoke(confirmAction.id)}>{confirmAction?.type==='clear'?'Clear Data':'Revoke Access'}</button></div></Modal><Modal open={hallOpen} title="Add Hall Section" subtitle="Each hall gets its own capacity range and booking conflict scope." onClose={()=>setHallOpen(false)}><form onSubmit={addHall}><label className="field"><span>Hall Name *</span><input required value={hall.name} onChange={e=>setHall({...hall,name:e.target.value})}/></label><div className="form-grid form-grid-2"><label className="field"><span>Minimum Capacity</span><input type="number" min="0" value={hall.minCapacity} onChange={e=>setHall({...hall,minCapacity:Number(e.target.value)})}/></label><label className="field"><span>Maximum Capacity *</span><input required type="number" min="1" value={hall.maxCapacity} onChange={e=>setHall({...hall,maxCapacity:Number(e.target.value)})}/></label></div><div className="modal-actions"><button type="button" className="btn" onClick={()=>setHallOpen(false)}>Cancel</button><button className="btn btn-primary">Add Hall</button></div></form></Modal>{toast?<Toast message={toast.m} type={toast.t} onClose={()=>setToast(null)}/>:null}</>;
}
