'use client';
import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { getResource } from '@/lib/client';
import { money, shortDate } from '@/lib/format';
import { PageHeader } from '@/components/ui/PageHeader';
import { Loading } from '@/components/ui/Loading';
import { Icon } from '@/components/ui/Icon';
import { Select } from '@/components/ui/Select';

export default function FunctionSheetsPage(){
 const params=useSearchParams();const[data,setData]=useState<any>(null);const[selected,setSelected]=useState(params.get('booking')||'');
 useEffect(()=>{getResource('operations').then((d:any)=>{setData(d);setSelected(s=>s||d.bookings[0]?.id||'')})},[]);
 const booking=useMemo(()=>data?.bookings.find((b:any)=>b.id===selected),[data,selected]);
 async function pdf(){if(!booking)return;const {jsPDF}=await import('jspdf');const doc=new jsPDF({unit:'mm',format:'a4'});let y=18;doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text(data.settings.legalName||data.settings.workspaceName,15,y);y+=8;doc.setFontSize(14);doc.text('FINAL FUNCTION SHEET',15,y);y+=9;doc.setFont('helvetica','normal');doc.setFontSize(10);const line=(label:string,value:string)=>{doc.setFont('helvetica','bold');doc.text(`${label}:`,15,y);doc.setFont('helvetica','normal');doc.text(value,52,y);y+=6};line('Booking',booking.code);line('Customer',booking.customerName);line('Phone',booking.phone);line('Date / Shift',`${booking.eventDate} / ${booking.shift}`);line('Hall',booking.hallName);line('Event',booking.eventType);line('Guests',String(booking.guests));line('Arrival',booking.arrivalTime||'—');line('Dinner',booking.dinnerTime||'—');line('Per Head',money(booking.perHeadRate,data.settings.currencySymbol));line('Total',money(booking.totalAmount,data.settings.currencySymbol));y+=3;doc.setFont('helvetica','bold');doc.text('MENU',15,y);y+=6;doc.setFont('helvetica','normal');for(const item of booking.menuSelections){doc.text(`• ${item.name} (${item.category})`,18,y);y+=5}y+=3;doc.setFont('helvetica','bold');doc.text('STAGE / DECOR',15,y);y+=6;doc.setFont('helvetica','normal');doc.text(booking.stageName||'No stage selected',18,y);y+=8;doc.setFont('helvetica','bold');doc.text('SPECIAL INSTRUCTIONS',15,y);y+=6;doc.setFont('helvetica','normal');const lines=doc.splitTextToSize(booking.specialInstructions||'No special instructions.',175);doc.text(lines,18,y);y+=lines.length*5+4;doc.setFont('helvetica','bold');doc.text('VENDOR TASKS',15,y);y+=6;doc.setFont('helvetica','normal');for(const t of booking.tasks){const v=t.vendor?.name||'Vendor';const txt=doc.splitTextToSize(`• ${v}: ${t.title} — ${t.instructions||'No notes'} [${t.status}]`,170);if(y+txt.length*5>285){doc.addPage();y=18}doc.text(txt,18,y);y+=txt.length*5+2}doc.save(`${booking.code}-function-sheet.pdf`)}
 if(!data)return <Loading/>;
 return <><PageHeader title="Function Sheets" description="A single final brief for floor manager, kitchen, decor and sound — generated from the live booking record." actions={<><div className="page-select-wrap"><Select value={selected} onChange={setSelected} options={data.bookings.map((b:any)=>({value:b.id,label:`${b.code} — ${b.customerName} — ${shortDate(b.eventDate)}`}))}/></div><button className="btn btn-primary" onClick={pdf} disabled={!booking}><Icon name="file-earmark-pdf"/>Download PDF</button></>}/>
 {booking?<section className="function-sheet panel"><div className="sheet-title"><div><span className="sheet-mark">{data.settings.initials}</span><div><h2>{data.settings.legalName}</h2><p>Final Function Sheet</p></div></div><span className={`status-pill ${booking.finalized?'status-confirmed':'status-hold'}`}>{booking.finalized?'Finalized':'Draft Operations'}</span></div><div className="sheet-grid"><Sheet label="Booking" value={booking.code}/><Sheet label="Customer" value={booking.customerName}/><Sheet label="Phone" value={booking.phone}/><Sheet label="Event" value={booking.eventType}/><Sheet label="Date" value={shortDate(booking.eventDate)}/><Sheet label="Shift" value={booking.shift}/><Sheet label="Hall" value={booking.hallName}/><Sheet label="Guests" value={booking.guests.toLocaleString()}/><Sheet label="Arrival" value={booking.arrivalTime||'—'}/><Sheet label="Dinner" value={booking.dinnerTime||'—'}/><Sheet label="Per Head" value={money(booking.perHeadRate,data.settings.currencySymbol)}/><Sheet label="Total" value={money(booking.totalAmount,data.settings.currencySymbol)}/></div><div className="sheet-columns"><div className="sheet-section"><h3>Menu</h3>{booking.menuSelections.length?<ul>{booking.menuSelections.map((m:any)=><li key={m.itemId}><span>{m.name}</span><small>{m.category}</small></li>)}</ul>:<p>No menu selections.</p>}</div><div className="sheet-section"><h3>Stage / Decor</h3><p><strong>{booking.stageName||'Not selected'}</strong></p><p>{booking.stageCost?money(booking.stageCost,data.settings.currencySymbol):'No separate stage charge'}</p></div></div><div className="sheet-section"><h3>Special Instructions</h3><p>{booking.specialInstructions||'No special instructions recorded.'}</p></div><div className="sheet-section"><h3>Vendor & Team Instructions</h3>{booking.tasks.length?<div className="task-sheet-list">{booking.tasks.map((t:any)=><div key={t.id}><strong>{t.vendor?.name||'Vendor'} — {t.title}</strong><span>{t.instructions||'No additional notes.'}</span><small>Status: {t.status}</small></div>)}</div>:<p>No tasks assigned yet.</p>}</div><div className="sheet-footer"><span>Generated from the live booking record.</span><span>{data.settings.phone}</span></div></section>:<div className="panel empty-state"><strong>No confirmed booking selected</strong><p>Create a confirmed booking first.</p></div>}
 </>;
}
function Sheet({label,value}:{label:string;value:string}){return <div className="sheet-field"><span>{label}</span><strong>{value}</strong></div>}
