'use client';
import { FormEvent, useEffect, useState } from 'react';
import { getResource, openWhatsApp, postAction } from '@/lib/client';
import { shortDate } from '@/lib/format';
import { PageHeader } from '@/components/ui/PageHeader';
import { Loading } from '@/components/ui/Loading';
import { Icon } from '@/components/ui/Icon';
import { Modal } from '@/components/ui/Modal';
import { Toast } from '@/components/ui/Toast';
import { Select } from '@/components/ui/Select';
import { DatePicker } from '@/components/ui/DatePicker';

const vendorCategories=['Decorator','Caterer','Sound','Lighting','Photographer','Other'].map(v=>({value:v,label:v}));
const taskStatuses=[{value:'pending',label:'Pending'},{value:'confirmed',label:'Confirmed'},{value:'done',label:'Done'}];
export default function VendorsPage(){
 const[data,setData]=useState<any>(null);const[openVendor,setOpenVendor]=useState(false);const[openTask,setOpenTask]=useState(false);const[vendorForm,setVendorForm]=useState({name:'',category:'Decorator',phone:'',notes:''});const[taskForm,setTaskForm]=useState({bookingId:'',vendorId:'',title:'',instructions:'',dueAt:''});const[toast,setToast]=useState<{m:string;t:'success'|'error'}|null>(null);
 async function load(){const d=await getResource('vendors');setData(d);setTaskForm(f=>({...f,bookingId:f.bookingId||d.bookings[0]?.id||'',vendorId:f.vendorId||d.vendors[0]?.id||''}))} useEffect(()=>{load()},[]);
 async function addVendor(e:FormEvent){e.preventDefault();try{await postAction('createVendor',vendorForm);setOpenVendor(false);setVendorForm({name:'',category:'Decorator',phone:'',notes:''});await load();setToast({m:'Vendor added.',t:'success'})}catch(e){setToast({m:e instanceof Error?e.message:'Could not add vendor',t:'error'})}}
 async function addTask(e:FormEvent){e.preventDefault();try{const r:any=await postAction('createVendorTask',taskForm);if(r.whatsapp?.link)openWhatsApp(r.whatsapp.link);setOpenTask(false);setTaskForm({...taskForm,title:'',instructions:'',dueAt:''});await load();setToast({m:r.whatsapp?.status==='sent'?'Task assigned and WhatsApp sent.':'Task assigned; WhatsApp message prepared.',t:'success'})}catch(e){setToast({m:e instanceof Error?e.message:'Could not assign task',t:'error'})}}
 async function status(id:string,s:string){try{await postAction('updateVendorTask',{id,status:s});await load()}catch(e){setToast({m:e instanceof Error?e.message:'Update failed',t:'error'})}}
 if(!data)return <Loading/>;
 return <><PageHeader title="Vendors & Tasks" description="Give decorators, kitchen and sound teams exact event instructions and track confirmation." actions={<><button className="btn" onClick={()=>setOpenVendor(true)}><Icon name="person-plus"/>Add Vendor</button><button className="btn btn-primary" onClick={()=>setOpenTask(true)} disabled={!data.vendors.length||!data.bookings.length}><Icon name="send"/>Assign Task</button></>}/>
 <div className="vendor-grid">{data.vendors.map((v:any)=><section className="panel vendor-card" key={v.id}><div className="vendor-icon"><Icon name={v.category==='Decorator'?'palette':v.category==='Caterer'?'egg-fried':v.category==='Sound'?'speaker':'briefcase'} size={20}/></div><div><strong>{v.name}</strong><span>{v.category}</span><p>{v.phone}</p><small>{v.notes}</small></div></section>)}</div>
 <section className="panel" style={{marginTop:12}}><div className="panel-head"><div><h2>Assigned Event Tasks</h2><p>Every instruction stays attached to its booking and vendor.</p></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Booking</th><th>Vendor</th><th>Task</th><th>Due</th><th>Status</th><th>Update</th></tr></thead><tbody>{data.tasks.map((t:any)=><tr key={t.id}><td><strong>{t.booking?.code||'—'}</strong><span className="cell-sub">{t.booking?.customerName||'—'}</span></td><td>{t.vendor?.name||'—'}<span className="cell-sub">{t.vendor?.category}</span></td><td><strong>{t.title}</strong><span className="cell-sub cell-wrap">{t.instructions||'No additional instructions'}</span></td><td>{t.dueAt?shortDate(t.dueAt):'—'}</td><td><span className={`status-pill ${t.status==='done'?'status-confirmed':t.status==='confirmed'?'status-hold':'status-draft'}`}>{t.status}</span></td><td><Select compact value={t.status} options={taskStatuses} onChange={v=>status(t.id,v)}/></td></tr>)}{!data.tasks.length?<tr><td colSpan={6}><div className="empty-row">No vendor tasks assigned yet.</div></td></tr>:null}</tbody></table></div></section>
 <Modal open={openVendor} title="Add Vendor" subtitle="Use internal departments as vendors too — e.g. Kitchen Operations." onClose={()=>setOpenVendor(false)}><form onSubmit={addVendor}><div className="form-grid form-grid-2"><label className="field"><span>Name *</span><input required value={vendorForm.name} onChange={e=>setVendorForm({...vendorForm,name:e.target.value})}/></label><label className="field"><span>Category</span><Select value={vendorForm.category} options={vendorCategories} onChange={v=>setVendorForm({...vendorForm,category:v})}/></label><label className="field"><span>WhatsApp / Phone *</span><input required value={vendorForm.phone} onChange={e=>setVendorForm({...vendorForm,phone:e.target.value})}/></label></div><label className="field"><span>Notes</span><textarea rows={3} value={vendorForm.notes} onChange={e=>setVendorForm({...vendorForm,notes:e.target.value})}/></label><div className="modal-actions"><button type="button" className="btn" onClick={()=>setOpenVendor(false)}>Cancel</button><button className="btn btn-primary">Add Vendor</button></div></form></Modal>
 <Modal open={openTask} title="Assign Vendor Task" subtitle="In WhatsApp link mode, the exact pre-filled message opens for one-click sending. Cloud API mode sends automatically." onClose={()=>setOpenTask(false)}><form onSubmit={addTask}><label className="field"><span>Booking *</span><Select value={taskForm.bookingId} options={data.bookings.map((b:any)=>({value:b.id,label:`${b.code} — ${b.customerName} — ${shortDate(b.eventDate)}`}))} onChange={v=>setTaskForm({...taskForm,bookingId:v})}/></label><label className="field"><span>Vendor *</span><Select value={taskForm.vendorId} options={data.vendors.map((v:any)=>({value:v.id,label:`${v.name} — ${v.category}`}))} onChange={v=>setTaskForm({...taskForm,vendorId:v})}/></label><div className="form-grid form-grid-2"><label className="field"><span>Task Title *</span><input required value={taskForm.title} onChange={e=>setTaskForm({...taskForm,title:e.target.value})} placeholder="Stage setup / Kitchen brief"/></label><label className="field"><span>Due Date</span><DatePicker value={taskForm.dueAt} onChange={v=>setTaskForm({...taskForm,dueAt:v})}/></label></div><label className="field"><span>Instructions</span><textarea rows={4} value={taskForm.instructions} onChange={e=>setTaskForm({...taskForm,instructions:e.target.value})} placeholder="Exact setup, timing and delivery instructions..."/></label><div className="modal-actions"><button type="button" className="btn" onClick={()=>setOpenTask(false)}>Cancel</button><button className="btn btn-primary">Assign & Send</button></div></form></Modal>{toast?<Toast message={toast.m} type={toast.t} onClose={()=>setToast(null)}/>:null}</>;
}
